[package]
name = "currency_core"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.39", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
thiserror = "2.0.11"
