[package]
name = "currency_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.28", features = ["derive"] }
ureq = "3.0.5"
currency_core = { path = "../currency_core" }
serde_json = "1.0.138"
thiserror = "2.0.11"
currency_api = { path = "../currency_api" }
